local game_config     = require("config.game_config")
local game_controller = require("controller.game_controller")
local game_manager    = require("manager.game_manager")
local game_state      = require("model.game_state")

function init(self)
	local state     = game_state.create()
	self.manager    = game_manager.create(game_config, state, os.time())
	self.controller = game_controller.create(self.manager)
	msg.post(".", "acquire_input_focus")
end

function update(self, dt)
	game_controller.update(self.controller, dt)
	self.manager:update()
end

function final(self)
	self.manager:final()
	self.controller = nil
	self.manager = nil
end
